require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - 'change_the_subject.gemspec'
  - 'tmp/**/*'

Layout/LineLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'lib/change_the_subject.rb'

Naming/RescuedExceptionsVariableName:
  Enabled: false
